### ISSUE TITLE
Q : Guest User Authentication

### ISSUE THREAD

**Issue by allantl22** [jamesward/play-rest-security#10]
How would i authenticate a guest user for my endpoint ? Any thoughts?

**Comment by jamesward** [comment]
Typically I don't use authentication for guest users.  Can you describe more about what you are looking for?

**Comment by allantl22** [comment]
I'm trying to build a forum-like web app, where user doesn't need to login to be able to view a topic(as a guest user). I'm not sure how would I authenticate this kind of request.

**Comment by jamesward** [comment]
I wouldn't do any authentication for that.  Just have the API be able to access certain data if there isn't an authorized user / auth token.
